# Generated by Django 3.2.3 on 2021-05-22 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название проекта')),
                ('link', models.URLField(verbose_name='ссылка')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='пользователи')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='текст заметки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo_app.project', verbose_name='проект')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
