# Generated by Django 3.2.3 on 2021-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='почта'),
        ),
    ]
